[package]
name = "bincode_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
path = "src/lib.rs" 

[dependencies]
bincode = { version = "2.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
cbindgen = "0.26"

